[WIP] Initial implementation of Hilbert detector
mne-tools/mne-hfo pull request #23
Opened 2021-03-12 15:08 UTC by pmyers16

PR Description
--------------

Implement the Hilbert Detector in the same 2-step approach as the other detectors.

Merge checklist
---------------

Maintainer, please confirm the following before merging:

- [ ] All comments resolved
- [ ] This is not your own PR
- [ ] All CIs are happy
- [ ] PR title starts with [MRG]
- [ ] [whats_new.rst](https://github.com/adam2392/mne-hfo/blob/master/doc/whats_new.rst) is updated
- [ ] PR description includes phrase "closes <#issue-number>"

2021-03-12 15:13 UTC, pmyers16 commented on mne_hfo/utils.py
> +def _band_zscore_detect(signal, sfreq, band_idx, l_freq, h_freq, n_times,
I did not quite fix the loop issue here, but I figured out how this works and tried to document it better.

2021-03-12 15:15 UTC, pmyers16 commented on mne_hfo/utils.py
> +def compute_hilbert(signal, extra_params):
This one is a bit different because you compute the metric per freq band, so the return ends up being an ndarray

2021-03-12 15:17 UTC, pmyers16 commented on mne_hfo/utils.py
> +
From here, we should have band indices, start and stop times, and max values during that band

2021-03-12 15:19 UTC, pmyers16 commented on mne_hfo/utils.py
> +def _run_detect_branch(detects, det_idx, HFO_outline):
I believe all this does is merge overlapping events

2021-03-12 15:19 UTC, pmyers16 commented on mne_hfo/utils.py
> +                                                        HFO_outline)))
From here, we should have the overlapping events merged together

2021-03-12 15:24 UTC, pmyers16 commented on mne_hfo/utils.py
> +        while sum(tdetects[:, 0] != 0):
I need to look more into what this function's purpose is...I don't see how tdetects is changing, so not sure how this loop would ever end

2021-03-12 15:27 UTC, pmyers16 commented on mne_hfo/utils.py
> +
This is where the additional info comes in. Hilbert calculates start and stop times, the frq band that the detection was found in, the max amplitude of the signal during this window, and the freq where that max amplitude occurred. Should we try to work this info into the output data structures?

2021-03-12 15:36 UTC, adam2392 commented on mne_hfo/detect.py
> +                 sfreq: float,
don't need.

2021-03-12 15:40 UTC, adam2392 commented on mne_hfo/detect.py
> +                                       method='iir', verbose=self.verbose)
can you remind me why iir vs fir for this one? 

Do they use IIR in the original implementation?

2021-03-12 15:40 UTC, adam2392 commented on mne_hfo/detect.py
> +                                       method='iir', verbose=self.verbose)
If so, just document it here perhaps inline comment.

2021-03-12 16:38 UTC, adam2392 commented on mne_hfo/utils.py
> +def _run_detect_branch(detects, det_idx, HFO_outline):
Yeah, let's see if we can refactor this then to use our version, which imo is more explicit. 

This recursion imo is completely unnecessary and hard to decipher heh

2021-03-12 16:38 UTC, adam2392 commented on mne_hfo/utils.py
> +def compute_hilbert(signal, extra_params):
Can you document what the array axes mean, so I can take a closer look?

2021-03-12 16:41 UTC, adam2392 commented on mne_hfo/utils.py
> +
So based on a threshold applied, the start/stop times can get converted to our `hfo_event_arr_`, while we can store in parallel a same-size array with freq-band (l_freq and h_freq) for each index, and the also another array with the same-size with the `max_amplitude` and also another array with the `freq` of the max amplitude.

We can either use these downstream, or scrap these and pipe them into a cohesive dataframe. This tbd, since I'm not sure how this would look, so better to be explicit rn.

2021-03-12 19:32 UTC, pmyers16 commented on mne_hfo/utils.py
> +
Just to be clear, you are proposing that a HilbertDetector would have additional objects assigned to it at the end of class. We put start/stop times into the `hfo_event_arr_` that we have been using. Then we have another array for freq bands and another array for amplitudes. Then we compare them just by matching row indices? Seems easy enough

2021-03-12 22:35 UTC, pemyers27 commented on mne_hfo/detect.py
> +                                       method='iir', verbose=self.verbose)
Yes, that is what was in the original implementation, so I can comment

2021-03-12 22:48 UTC, pemyers27 commented
So right now, `_post_process_ch_hfos` simply calls the `threshold_func` to determine the threshold, then applies this threshold to the data to identify events. Obviously this is too simple for a Hilbert detector, or something more complex. My initial attempt seems slightly wrong, so what do you think about this workflow.
`if threshold-method == '<method>':
    threshold_det_func = threshold_det_<method>
    event_identification_func = event_identification_<method>
    event_merging_func = event_merging_<method>
    extra_params = dict(values=values,...)
`
This will allow us to keep things simple for RMS/Line Length Detectors, but allow for any level of complexity at each step for the more complicated detectors.

2021-03-15 01:54 UTC, adam2392 commented on mne_hfo/utils.py
> +
Yep. These can all be "additional" data structures that are unique to just Hilbert detectors. We can later figure out how to best combine these if one would need programmatic access to it when doing post-hoc anallysis.

2021-03-15 02:15 UTC, adam2392 commented
> So right now, `_post_process_ch_hfos` simply calls the `threshold_func` to determine the threshold, then applies this threshold to the data to identify events. Obviously this is too simple for a Hilbert detector, or something more complex. My initial attempt seems slightly wrong, so what do you think about this workflow.
> `if threshold-method == '<method>': threshold_det_func = threshold_det_<method> event_identification_func = event_identification_<method> event_merging_func = event_merging_<method> extra_params = dict(values=values,...) `

Would you mind explaining to me with some more detail here? I'm not quite following. So Hilbert rn requires 3 thresholds: i) zscore of the Hilbert transform envelope, ii) number of cycles found and iii) gaps (idr what gaps were, so maybe we need to document that better). 

The issue is `_post_process_ch_hfos` performs thresholding of only one metric. It seems based on our convos so far, that Hilbert needs to store the output of the thresholding step? Or how is the thresholding step connected to later on? 

If thresholding needs to be a distinct step in of itself, then we can have each `fit` be: i) `_compute_hfo_metrics`, ii) threshold and iii) post_process into HFO detections. Would that work? You then can i) refactor the threshold step for all detectors out of the `_post_proc` function and then ii) refactor the `_band_z_score_detect` function into `postprocess`?

If I'm missing anything, lmk.

2021-03-17 19:30 UTC, pmyers16 commented
So the basic idea of `_run_detect_branch` is to find the entire freq band that the HFO occurred in. Each freq band has a `band_idx`, so the goal is to check if there exists `eventi[band_idx], eventj[band_idx+1]` that overlap, and the recursion allows that to keep going for `eventi[band_idx], eventj[band_idx+1], eventk[band_idx+2], ....` is equal to one event

Once the overlapping events are merged, the HFO is defined as the [min start time, max end time] and the freq band is defined as [l_freq(band_idx), h_freq(band_idx+(n-1)]  for n overlapping events.

Unfortunately I don't think computational efficiency is going to be good for this no matter what, but this is generally the new idea:
`#  For simplicity lets assume each detection has the form [start, stop, band_idx]`
`outlines = list`
`for detection in detections:`
`----if band_idx is 0:`
`--------append detection to outlines`
`----else:`  
`--------for outline in outlines:`
`------------if detection overlaps outline:`
`----------------merge detection and outline`
`------------else:`
`----------------append detection to outlines`

Then outlines should only have distinct HFO events

2021-03-21 01:05 UTC, adam2392 commented on mne_hfo/base.py
> +        """Post process one channel's HFO events.
```suggestion
        """Post process one channel's HFO events after thresholding.
```

2021-03-21 01:06 UTC, adam2392 commented on mne_hfo/base.py
> +    def _apply_threshold(self, metric, threshold_method):
Is this for a single channel? If so, documentation can be made more explicit.

If not, we should implement just for a single channel.

2021-03-21 01:08 UTC, adam2392 commented on mne_hfo/base.py
> +            return detections
we don't merge time-windows?

2021-03-21 01:10 UTC, adam2392 commented on mne_hfo/detect.py
> +            self.freq_span = (filter_band[1] - filter_band[0]) - 1
This looks good, but will not work because goes against sklearn-style API. Stick inside `fit()` at the beginning instead.

2021-03-21 01:11 UTC, adam2392 commented on mne_hfo/detect.py
> +            self.freq_span = (filter_band[1] - filter_band[0]) - 1
Meaning, sklearn imposes that one does not define additional things inside `__init__` except what is passed in. Not sure why, but just something to do w/ it's API compliance.

2021-03-21 01:15 UTC, adam2392 requested changes
Some changes, but overall looks good, especially if unit tests are still passing. 

Can you also add to the docstring of `Detector`, the general flow of an algorithm? This way, any downstream Detectors follow this abstraction.

E.g.
```
Step 1: compute a statistic on the data
Step 2: ...
etc.
```

Once you also add unit tests for Hilbert and validate that this works, then LGTM.

2021-03-25 13:59 UTC, pmyers16 commented on mne_hfo/detect.py
> +            self.freq_span = (filter_band[1] - filter_band[0]) - 1
Should I stick it in Hilbert's `_compute_hfo_statistic` function? That way we avoid a bunch of if statements in the base fit method

2021-03-25 14:02 UTC, adam2392 commented on mne_hfo/detect.py
> +            self.freq_span = (filter_band[1] - filter_band[0]) - 1
Sure that makes sense, unless there's any logic in fit that relies on this before calling `_compute_hfo_statistic`.

2021-03-25 14:03 UTC, pmyers16 commented on mne_hfo/base.py
> +            return detections
We do, but we do it upstream. I left a TODO where its done to refactor it here if you wanted. I think refactoring will slow it down a bit, which is why I held off

2021-03-25 14:04 UTC, pmyers16 commented on mne_hfo/detect.py
> +            self.freq_span = (filter_band[1] - filter_band[0]) - 1
Nope, it just calls `_check_input_raw`, then right into `_compute_hfo_statistic`

2021-03-25 14:09 UTC, adam2392 commented on mne_hfo/base.py
> +            return detections
Hmm okay I will take a look

2021-03-30 15:25 UTC, pmyers16 commented on mne_hfo/utils.py
> +        hfx = np.abs(hilbert(signal))
This step is what was throwing the memory error

2021-03-31 21:41 UTC, adam2392 commented
If you fix the CI and resolve the resolved comments, then I can take another review. Can merge and then we can move on with other high pri tasks.

2021-04-01 20:55 UTC, adam2392 commented
Looks like `_band_zscore_detect` in utils.py isn't covered. I think you don't need that anymore right since you refactored things?

2021-04-01 21:07 UTC, pmyers16 commented
> Looks like `_band_zscore_detect` in utils.py isn't covered. I think you don't need that anymore right since you refactored things?

No, it is used by `apply_hilbert` function. I can test

2021-04-06 14:45 UTC, adam2392 commented on mne_hfo/base.py
> +        """Compute detections on an individual channel data.
```suggestion
        """Compute detections on an individual channel data using a sliding window.
```

2021-04-06 14:45 UTC, adam2392 commented on mne_hfo/base.py
> +            Data from a single channel
```suggestion
            Data (1D array) from a single channel
```

2021-04-06 14:46 UTC, adam2392 commented on mne_hfo/base.py
> +            Method used to compute the detection
```suggestion
            Method used to compute the detection. Can be one of ``'line_length', 'rms', 'hilbert'``.
```

2021-04-06 14:46 UTC, adam2392 commented on mne_hfo/base.py
> +            Method to use to merge the detections.
```suggestion
            Method to use to merge the detections. Can be one of ``'time-windows', 'freq-bands'``.
```

2021-04-06 14:48 UTC, adam2392 approved these changes

2021-04-06 15:59 UTC, merged